### ISSUE TITLE
code copy functionality implementation

### ISSUE THREAD

**Issue by saifullahsiddique** [saifullahsiddique/css-box-shadow-generator-by-react#17]

**Comment by Sathasivamthirumoorthi** [comment]
since I am new to open source , i would like to work on this .....

**Comment by Sathasivamthirumoorthi** [comment]
can i know . what was the issue actually . thanks in advance :)

**Comment by saifullahsiddique** [comment]
@Sathasivamthirumoorthi  Sure. You can implement the code copy functionality on this project. You're always welcome to contribute. Please, implement the copy functionality and make a pull request there. 

Thanks for reaching here. I'm excited to add your implementation to the project.

**Comment by Sathasivamthirumoorthi** [comment]
yeah. thank you ...

**Comment by saifullahsiddique** [comment]
You're welcome.
